#查询系列api，每6小时调用一次（周六日不启动）
name: Run Api.Read

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: '12 */6 * * 1-5'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests #安装requests模块
      run: |
        pip install requests
    - name: run api.Read #api调用
      env: 
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        ACCOUNT: ${{ secrets.ACCOUNT }} 
        ACCOUNT_ADD: ${{ secrets.ACCOUNT_ADD }} 
        ACCOUNT_DEL: ${{ secrets.ACCOUNT_DEL }} 
        REDIRECT_URI: ${{ secrets.REDIRECT_URL }}   
        OTHER_CONFIG: ${{ secrets.OTHER_CONFIG }}  
        EMAIL: ${{ secrets.EMAIL }}  
        TG_BOT: ${{ secrets.TG_BOT }}   
      run: |
        python ApiOfRead.py
