#创建系列api，每天调用一次
name: Run Api.Write

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: '12 23 * * *'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests and xlsxwriter #安装模块
      run: |
        pip install requests
        pip install xlsxwriter
    - name: run api.Write #api调用
      env:              
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        ACCOUNT: ${{ secrets.ACCOUNT }} 
        ACCOUNT_ADD: ${{ secrets.ACCOUNT_ADD }} 
        ACCOUNT_DEL: ${{ secrets.ACCOUNT_DEL }} 
        REDIRECT_URI: ${{ secrets.REDIRECT_URL }}   
        OTHER_CONFIG: ${{ secrets.OTHER_CONFIG }}  
        EMAIL: ${{ secrets.EMAIL }}  
        TG_BOT: ${{ secrets.TG_BOT }}  
      run: |
        python ApiOfWrite.py
